// Auto-generated API types and client
// DO NOT MODIFY - This file is automatically generated

export * from './client';
export type { paths, components } from './schema';

// Re-export commonly used types for convenience
export type {
  LoginRequest,
  LoginResponse,
  RegisterRequest,
  UserProfileResponse,
  ApiPaths,
} from './client';